package joyclub.pokerstarsleaguecalculator;
/**
 *
 * @author nicola
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLPremiati = new javax.swing.JLabel();
        jLPunti = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTIscritti = new javax.swing.JFormattedTextField();
        jTRimasti = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PokerStars League Calculator");
        setResizable(false);
        setSize(new java.awt.Dimension(263, 216));

        jLPremiati.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLPremiati.setForeground(java.awt.Color.red);
        jLPremiati.setText("0");

        jLPunti.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLPunti.setForeground(java.awt.Color.red);
        jLPunti.setText("0");

        jLabel1.setText("Iscritti");

        jLabel2.setText("Posizione");

        jLabel3.setText("A Premio");

        jLabel4.setText("Punti");

        jTIscritti.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jTIscritti.setAutoscrolls(false);
        jTIscritti.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTIscritti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIscrittiActionPerformed(evt);
            }
        });

        jTRimasti.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jTRimasti.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTRimasti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRimastiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(jTRimasti, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPunti)
                            .addComponent(jLPremiati)
                            .addComponent(jTIscritti, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTIscritti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTRimasti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPremiati)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPunti)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTIscrittiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIscrittiActionPerformed
        // TODO add your handling code here:
        PuntiLeague aPunti = new PuntiLeague();
        String strIscritti = jTIscritti.getText();
        int iscritti = Integer.parseInt(strIscritti);
        int premiati = aPunti.aPremio(iscritti);
        String strPremiati = Integer.toString(premiati);
        jLPremiati.setText(strPremiati);        
    }//GEN-LAST:event_jTIscrittiActionPerformed

    private void jTRimastiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRimastiActionPerformed
        // TODO add your handling code here:
        PuntiLeague aPunti = new PuntiLeague();
        String strIscritti = jTIscritti.getText();
        int iscritti = Integer.parseInt(strIscritti);
        int premiati = aPunti.aPremio(iscritti);
        String strPosizione = jTRimasti.getText();
        int posizione = Integer.parseInt(strPosizione);
        if (posizione <= premiati) {
            double puntiAssegnati = aPunti.puntiAssegnati(iscritti, posizione);
            String strPuntiAssegnati = Double.toString(puntiAssegnati);
            jLPunti.setText(strPuntiAssegnati);
        }
        else jLPunti.setText("0");        
    }//GEN-LAST:event_jTRimastiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    public class PuntiLeague {

        int premiati;
        double puntiAssegnati;

        int aPremio(int iscritti) {
            premiati = (iscritti * 15) / 100;
            return premiati;
        }

        double puntiAssegnati(int iscritti, int posizione) {
            puntiAssegnati = 10 * (Math.sqrt(iscritti) / Math.sqrt(posizione));
            return puntiAssegnati;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLPremiati;
    private javax.swing.JLabel jLPunti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField jTIscritti;
    private javax.swing.JFormattedTextField jTRimasti;
    // End of variables declaration//GEN-END:variables
}
