/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package joyclub.pokerstarsleaguecalculator;

/**
 *
 * @author nicola
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTIscritti = new javax.swing.JTextField();
        jLPremiati = new javax.swing.JLabel();
        jTRimasti = new javax.swing.JTextField();
        jLPunti = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PokerStars League Calculator");

        jTIscritti.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTIscritti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIscrittiActionPerformed(evt);
            }
        });

        jLPremiati.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLPremiati.setForeground(java.awt.Color.red);
        jLPremiati.setText("A premio");

        jTRimasti.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTRimasti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRimastiActionPerformed(evt);
            }
        });

        jLPunti.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLPunti.setForeground(java.awt.Color.red);
        jLPunti.setText("Punti");

        jLabel1.setText("Iscritti");

        jLabel2.setText("Posizione");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPunti)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLPremiati)
                        .addComponent(jTIscritti)
                        .addComponent(jTRimasti, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTIscritti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPremiati)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRimasti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLPunti)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTIscrittiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIscrittiActionPerformed
        // TODO add your handling code here:
        PuntiLeague aPunti=new PuntiLeague();
        String strIscritti= jTIscritti.getText();
        int iscritti=Integer.parseInt(strIscritti);
        int premiati=aPunti.aPremio(iscritti);
        String strPremiati=Integer.toString(premiati);
        jLPremiati.setText(strPremiati);
    }//GEN-LAST:event_jTIscrittiActionPerformed

    private void jTRimastiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRimastiActionPerformed
        // TODO add your handling code here:
        PuntiLeague aPunti=new PuntiLeague();
        String strIscritti= jTIscritti.getText();
        int iscritti=Integer.parseInt(strIscritti);
        String strPosizione= jTRimasti.getText();
        int posizione=Integer.parseInt(strPosizione);
        double puntiAssegnati=aPunti.puntiAssegnati(iscritti,posizione);
        String strPuntiAssegnati=Double.toString(puntiAssegnati);
        jLPunti.setText(strPuntiAssegnati);
    }//GEN-LAST:event_jTRimastiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    public class PuntiLeague {
        
        int premiati;
        double puntiAssegnati;

        int aPremio(int iscritti) {
            premiati=(iscritti*15)/100;
            return premiati;
        }
        
        double puntiAssegnati(int iscritti,int posizione){
            puntiAssegnati=10*(Math.sqrt(iscritti)/Math.sqrt(posizione));
            return puntiAssegnati;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLPremiati;
    private javax.swing.JLabel jLPunti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTIscritti;
    private javax.swing.JTextField jTRimasti;
    // End of variables declaration//GEN-END:variables
}
